// ─────────────────────────────────────────────────────────────────────────────
// gcodeParser.ts  — v2
// Lê os comentários de cabeçalho de arquivos .gcode gerados pelos principais
// slicers: BambuStudio, PrusaSlicer, OrcaSlicer, Cura, SuperSlicer, IdeaMaker.
// ─────────────────────────────────────────────────────────────────────────────

export interface GcodeMetadata {
  /** Peso total do filamento em gramas */
  pesoG?: number;
  /** Comprimento do filamento em mm */
  comprimentoMm?: number;
  /** Tempo de impressão em horas (decimal) */
  tempoHoras?: number;
  /** Tipo de filamento: "PLA", "PETG", etc. */
  tipoFilamento?: string;
  /** Diâmetro do bico em mm */
  diametroNozzle?: number;
  /** Altura de camada em mm */
  alturaLayer?: number;
  /** Nome do slicer que gerou o arquivo */
  slicerNome?: string;
}

// ─── Parse da string de tempo ─────────────────────────────────────────────────
// Suporta: "5h 20m 10s" | "2h 19m 2s" | "30m" | "7036" (segundos)
function parseTimeString(str: string): number {
  const hm = str.match(/(\d+)\s*h/i);
  const mm = str.match(/(\d+)\s*m(?!s)/i);   // "m" mas não "ms"
  const sm = str.match(/(\d+)\s*s(?!\S)/i);  // "s" no fim ou antes de espaço

  let hours = 0;
  if (hm) hours += parseInt(hm[1]);
  if (mm) hours += parseInt(mm[1]) / 60;
  if (sm) hours += parseInt(sm[1]) / 3600;

  // Fallback: número puro = segundos (ex: Cura ;TIME:7036)
  if (!hm && !mm && !sm) {
    const n = parseFloat(str.trim());
    if (!isNaN(n)) hours = n / 3600;
  }

  return +hours.toFixed(4);
}

// ─── Estimativa de peso a partir do comprimento (Cura) ───────────────────────
// Assume filamento 1.75 mm PLA (densidade 1.24 g/cm³)
function mmParaGramas(mm: number): number {
  const raio    = 0.175 / 2;   // cm
  const volumeCm3 = Math.PI * raio ** 2 * (mm / 10);
  return +(volumeCm3 * 1.24).toFixed(2);
}

// ─── Tenta extrair um campo de uma string "chave = valor" ou "chave : valor" ──
function extrairValor(seg: string, chave: RegExp): string | null {
  const m = seg.match(chave);
  return m ? m[1].trim() : null;
}

// ─── Parser principal ─────────────────────────────────────────────────────────
// Lê apenas as primeiras 600 linhas (cabeçalho) — ~80 KB max.
export function parseGcode(text: string): GcodeMetadata {
  const meta: GcodeMetadata = {};
  const lines = text.split('\n').slice(0, 600);

  for (const raw of lines) {
    const line = raw.trim();
    if (!line.startsWith(';')) continue;

    // Conteúdo completo após o ";" inicial
    const c = line.slice(1).trim();
    let m: RegExpMatchArray | null;

    // ══════════════════════════════════════════════════════════════════════════
    // BAMBU STUDIO — header block (linhas 1–14)
    // O BambuStudio pode colocar MÚLTIPLOS campos numa mesma linha separados
    // por ";" — ex: "model printing time: 2h 12m 45s; total estimated time: 2h 19m 2s"
    // Portanto usamos regex SEM âncora ^ quando o campo pode não ser o primeiro.
    // ══════════════════════════════════════════════════════════════════════════

    // ; BambuStudio 02.05.03.61  (nome sem "generated by")
    m = c.match(/^(BambuStudio|OrcaSlicer|Bambu Studio)\s+([\d.]+)/i);
    if (m) { meta.slicerNome = `${m[1]} ${m[2]}`; continue; }

    // ; total estimated time: 2h 19m 2s  (pode aparecer após outro campo na mesma linha)
    m = c.match(/total estimated time:\s*([^;]+)/i);
    if (m && meta.tempoHoras === undefined) {
      meta.tempoHoras = parseTimeString(m[1].trim());
      continue;
    }

    // ; total filament weight [g] : 66.70   (usa " : " com espaço, não "=")
    m = c.match(/^total filament weight\s*\[g\]\s*[=:]\s*([\d.]+)/i);
    if (m && meta.pesoG === undefined) { meta.pesoG = parseFloat(m[1]); continue; }

    // ; total filament length [mm] : 22361.97
    m = c.match(/^total filament length\s*\[mm\]\s*[=:]\s*([\d.]+)/i);
    if (m) { meta.comprimentoMm = parseFloat(m[1]); continue; }

    // ; model printing time: 2h 12m 45s  (tempo de modelo, fallback se não tiver total)
    m = c.match(/^model printing time:\s*([^;]+)/i);
    if (m && meta.tempoHoras === undefined) {
      meta.tempoHoras = parseTimeString(m[1].trim());
      continue;
    }

    // ; CONFIG_VERSION → identifica BambuStudio (caso nome não apareça)
    if (/^CONFIG_VERSION/i.test(c)) { meta.slicerNome ||= 'BambuStudio'; continue; }

    // ══════════════════════════════════════════════════════════════════════════
    // PRUSASLICER / SUPERSLICER / ORCASLICER — config block
    // ══════════════════════════════════════════════════════════════════════════

    // ; filament used [g] = 4.74
    m = c.match(/^filament used \[g\]\s*=\s*([\d.]+)/i);
    if (m) { meta.pesoG = parseFloat(m[1]); continue; }

    // ; total filament used [g] = 4.74  (multi-extrusor)
    m = c.match(/^total filament used \[g\]\s*=\s*([\d.]+)/i);
    if (m && meta.pesoG === undefined) { meta.pesoG = parseFloat(m[1]); continue; }

    // ; filament used [mm] = 1590.68
    m = c.match(/^filament used \[mm\]\s*=\s*([\d.]+)/i);
    if (m) { meta.comprimentoMm = parseFloat(m[1]); continue; }

    // ; estimated printing time (normal mode) = 5h 20m 10s
    m = c.match(/^estimated printing time \(normal mode\)\s*=\s*(.+)/i);
    if (m) { meta.tempoHoras = parseTimeString(m[1].trim()); continue; }

    // ; estimated printing time = ...  (OrcaSlicer simplificado)
    m = c.match(/^estimated printing time\s*=\s*(.+)/i);
    if (m && meta.tempoHoras === undefined) { meta.tempoHoras = parseTimeString(m[1].trim()); continue; }

    // ; filament_type = PLA  (ou PLA;PLA para multi-extrusor → pega o 1º)
    m = c.match(/^filament_type\s*=\s*(.+)/i);
    if (m) { meta.tipoFilamento = m[1].trim().split(';')[0].trim(); continue; }

    // ; nozzle_diameter = 0.4
    m = c.match(/^nozzle_diameter\s*=\s*([\d.]+)/i);
    if (m) { meta.diametroNozzle = parseFloat(m[1]); continue; }

    // ; layer_height = 0.2
    m = c.match(/^layer_height\s*=\s*([\d.]+)/i);
    if (m) { meta.alturaLayer = parseFloat(m[1]); continue; }

    // ; generated by PrusaSlicer 2.7.0 on ...
    m = c.match(/^generated by\s+(.+?)(?:\s+on\s+|\s*$)/i);
    if (m) { meta.slicerNome = m[1].trim(); continue; }

    // ══════════════════════════════════════════════════════════════════════════
    // CURA
    // ══════════════════════════════════════════════════════════════════════════

    // ;FLAVOR:Marlin
    m = c.match(/^FLAVOR:(.+)/i);
    if (m) { meta.slicerNome ||= 'Cura'; continue; }

    // ;TIME:7036  (segundos totais)
    m = c.match(/^TIME:(\d+)$/);
    if (m && meta.tempoHoras === undefined) { meta.tempoHoras = parseTimeString(m[1]); continue; }

    // ;Filament used: 1.20047m  →  estima gramas
    m = c.match(/^Filament used:\s*([\d.]+)m$/i);
    if (m) {
      meta.comprimentoMm = parseFloat(m[1]) * 1000;
      if (meta.pesoG === undefined) meta.pesoG = mmParaGramas(meta.comprimentoMm);
      continue;
    }

    // ;Layer height: 0.12
    m = c.match(/^Layer height:\s*([\d.]+)/i);
    if (m) { meta.alturaLayer ||= parseFloat(m[1]); continue; }

    // ══════════════════════════════════════════════════════════════════════════
    // IDEAMAKER
    // ══════════════════════════════════════════════════════════════════════════

    // ;Printing Time: 1h 30m 0s
    m = c.match(/^Printing Time:\s*(.+)/i);
    if (m && meta.tempoHoras === undefined) { meta.tempoHoras = parseTimeString(m[1].trim()); continue; }

    // ;Material#1 Used: 4.74g
    m = c.match(/^Material#\d+ Used:\s*([\d.]+)g/i);
    if (m && meta.pesoG === undefined) { meta.pesoG = parseFloat(m[1]); continue; }

    // ══════════════════════════════════════════════════════════════════════════
    // GENÉRICO (fallback)
    // ══════════════════════════════════════════════════════════════════════════

    // ; print_time = 12345  (alguns custom firmwares, valor em segundos)
    m = c.match(/^print[_\s]?time\s*[=:]\s*([\d.]+)\s*$/i);
    if (m && meta.tempoHoras === undefined) { meta.tempoHoras = parseTimeString(m[1]); continue; }

    // Extrai tipo de filamento de qualquer "filament.*type" presente no campo
    if (!meta.tipoFilamento) {
      m = c.match(/filament[_\s]type\s*[=:]\s*(\w+)/i);
      if (m && /^(PLA|PETG|ABS|ASA|TPU|Nylon|PA|PC|HIPS|PVA|FLEX)/i.test(m[1])) {
        meta.tipoFilamento = m[1].toUpperCase();
      }
    }
  }

  return meta;
}

// ─── Formata horas decimais para exibição ("2h 19min") ──────────────────────
export function formatarTempo(horas: number): string {
  if (!horas || horas <= 0) return '0min';
  const h = Math.floor(horas);
  const m = Math.round((horas - h) * 60);
  if (h === 0) return `${m}min`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}min`;
}
